### PR TITLE
Fix error dequeuing job

### PR DESCRIPTION
**Pull request by bottlehall**
Issue #21 linked.

### CODE REVIEW

**Comment by maximedegreve** [comment]
This works 🎉 

@m-barthelemy Could you merge this in for a new release?

**Comment by m-barthelemy** [comment]
I was having a little bit of trouble setting up my project using this package on my new M1 device.
Making good progress now; will test, validate and then create a new release if all good.
Since this changes the format of the jobs data, it will have to be a major release.

**Comment by bottlehall** [comment]
I’m not sure the existing version is useable with this error for on-demand jobs. So, could a major release be avoided as the underlying column is unchanged and any scheduled jobs’ data would be unaffected?

**Comment by m-barthelemy** [comment]
> I’m not sure the existing version is useable with this error for on-demand jobs. So, could a major release be avoided as the underlying column is unchanged and any scheduled jobs’ data would be unaffected?
> […](#)

It would be disruptive for people upgrading to the new release but that still have pending jobs: these won't be able to get read anymore.

**Pull request merged**
