### PR TITLE
Comment out transaction commit in SQLITE pop

### LINKED ISSUE #9: SQLITE should be supported
In the readme there is a note that SQLITE is not currently working however I think with a small change it can be made working, even if it is not safe because of no transactions it will be useful for unit tests.

We can change this code in SqlitePop

                return db.execute(sql: updateQuery) { (row) in }
                    .map {
                        //return db.raw(SQLQueryString("COMMIT")).run().map {
                            return id
                        //}
                    }

to this

                return db.execute(sql: updateQuery) { (row) in }
                    .flatMap {
                        return db.raw(SQLQueryString("COMMIT")).run().map {
                            return id
                        }
                    }

I checked and this works nicely for unit tests especially if you will use in process worker. Thanks!

### PR DESCRIPTION
**Pull request by thuotdwz**
This will allow SQLITE for use in unit testing Fixes #9

### CODE REVIEW

**Comment by m-barthelemy** [comment]
I think the `COMMIT` here shouldn't be uncommented, since there's no transaction involved.

Instead, the Sqlite code should probably be changed and wrapped into a transaction like what is done in `MySQLPopQuery.swift`.
If you have the time and willingness to try updating the PR and test it, I'll happily approve and merge the change!

**Comment by thuotdwz** [comment]
Unfortunately if done in transaction app will hang when using in process worker, I am not sure why this happens :(

**Comment by m-barthelemy** [comment]
That's exactly why SQLite is not supported. To work properly the SQL statements must be wrapped in a transaction, otherwise multiple Queues worker would pickup the same job.

The problem is, when running it in process or a separate worker, you get 2xCpuCores Queues workers, all trying to poll SQLitefor new jobs to run at the same time, which causes a deadlock. SQLite has very limited support for concurrent requests.

The only way SQLite could possibly work is if you only have 1 single Queue worker.

**Comment by thuotdwz** [comment]
actually I tried with wal mode (PRAGMA journal_mode=WAL;) and single in process worker and seems it is working now with transaction!

so I copied over transaction from mysql as you suggested before and updated the patch

**Pull request merged**
